# Generated by Django 2.2 on 2022-05-24 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_auto_20220523_2238'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='additional_description',
            field=models.TextField(default='Test description'),
            preserve_default=False,
        ),
    ]
