# Generated by Django 2.2 on 2022-05-24 06:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_item_additional_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='additional_description',
        ),
    ]
