# Generated by Django 2.2 on 2022-05-24 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_remove_item_additional_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='additional_description',
            field=models.TextField(default='Lorem ipsum dolor sit amet consectetur adipisicing elit. Natus suscripit modi sapiente illo soluta odit voluptates, quibusdam officia. Nesque quibusdam quas a quis porro? Molestias illo neque eum in laborum.'),
            preserve_default=False,
        ),
    ]
